name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild ./solution.sln /m /p:Configuration=Debug /p:Platform=x64

      - name: Run tests
        run: |
          $dlls = Get-ChildItem -Recurse -Filter *test.dll
          foreach ($d in $dlls) { vstest.console.exe "$($d.FullName)" }
